http:
  port: "8082"

salesforce:
  username: "patilsuchitap-w04d@force.com"
  password: "Test@987"
  token:  "LehqNAjPO8R8nfbWylr0U10a7"
  host: https://test.salesforce.com/services/oauth2/token
  

  
  
  